### PR TITLE
Hello Microverse

### PR DESCRIPTION
**Pull request by mesfin345**
Hello Microverse Project
in this project I :
>used linters to check errors
>add a text and style it

### CODE REVIEW

**Review by micheaol — CHANGES_REQUESTED** [review]
Hi @mesfin345 , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!


## TO HIGHLIGHT: 
- Your project is professional 💯 
- Well structured files 💯 

## Required Changes ♻️
- Please ensure you always add a short summary of changes introduced in the pull request. Please this [LINK](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/documentation/articles/professional_repo_rules.md) for help.

## Example: 
pre

- Please ensure that your branch name should be descriptive (e.g.: refactor-authentication, user-content-cache-key, make-retina-avatars), so that others can see what is being worked on.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

**Comment by mesfin345** [comment]
Hello Microverse Project 
  in this project I : 
        >used linters to check errors
        >add a text and style it

**Review by thecodechaser — CHANGES_REQUESTED** [review]
## Hi @mesfin345 👋, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Required Changes ♻️
- [ ] As requested by the previous reviewer, Please ensure that your branch name should be descriptive (e.g.: hello-microverse), so that others can see what is being worked on.
Right now your branch is called a feature, Please rename it. To rename your branch [Click here](https://github.com/mesfin345/Hello-Microverse-Project/branches)

- [x]  As requested by the previous reviewer, Pull Request should have a descriptive title and description telling you what changes are inside. Please add a description to the Pull Request.

See the image for reference where to add a description
InkedScreenshot (41)

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._
- [ ] Please use camel case for your commit messages
Example: "Add HTML file" ✅ 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by mahbubul14** [comment]
# Project Approved :trophy: 

Hi @mesfin345 
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

**Pull request merged**
